### ISSUE TITLE
Add support for qBittorrent

### ISSUE THREAD

**Issue by AN1MATEK** [rpatterson/prunerr#1]
Hello there!

This tool does very well in a lot of scenarios where qBittorrents users have to use many programs together just to mimic a fraction of its power. 

I know this is a long shot, surely many will welcome this addition someday.

Using qbittorrent-api as the heavy lifter for the potation could be a great starting point: https://qbittorrent-api.readthedocs.io/en/latest/

Nevertheless thanks a LOT for the development efforts already invested in here.

**Comment by rpatterson** [comment]
See [the Contributing section of the README](https://gitlab.com/rpatterson/prunerr#contributing).  This is a mirror, please resubmit this feature request in the official/cannonical project.
